# # # # # # name='laxman'
# # # # # # print(name)
# # # # # name='saroj'
# # # # # print(name[-5])
# # # # # slicing {start end step}
# # # # # name='saroj'
# # # # # print(name[1:2])
# # # # name='saroj'
# # # # print(name[3:1])
# # # # name='saroj'
# # # # print(name[3:-2:-2]) #empty
# # # name='saroj'
# # # print(name[3:-2:2])
# # name= 'programming'
# # print(name[-19:2:2])
# name= 'programming'
# print(name[-12::-4])

